<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZCBLRLP0293" failures="0" tests="2" name="zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_pointVerificationAfterRedeemingPoints" time="23.820" errors="1" timestamp="2024-07-16T16:00:52 IST" skipped="0">
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_pointVerificationAfterRedeemingPoints" name="afterSuite" time="23.812">
    <error message="Unable to calculate MD5 hash: target\surefire-reports\awstests\awstests.html (The system cannot find the path specified)" type="com.amazonaws.SdkClientException">
      <![CDATA[com.amazonaws.SdkClientException: Unable to calculate MD5 hash: target\surefire-reports\awstests\awstests.html (The system cannot find the path specified)
at com.amazonaws.services.s3.AmazonS3Client.getInputStream(AmazonS3Client.java:1919)
at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1837)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1816)
at zapcg.Capillary.utils.ReportUploader.sendTestNGReports(ReportUploader.java:57)
at zapcg.Capillary.Base.BaseTest.afterSuite(BaseTest.java:107)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:386)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.io.FileNotFoundException: target\surefire-reports\awstests\awstests.html (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
at com.amazonaws.util.Md5Utils.computeMD5Hash(Md5Utils.java:97)
at com.amazonaws.util.Md5Utils.md5AsBase64(Md5Utils.java:104)
at com.amazonaws.services.s3.AmazonS3Client.getInputStream(AmazonS3Client.java:1915)
... 23 more
]]>
    </error>
  </testcase> <!-- afterSuite -->
  <testcase classname="zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_pointVerificationAfterRedeemingPoints" name="verify_TotalPoints_Before_and_After" time="0.008"/>
</testsuite> <!-- zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_pointVerificationAfterRedeemingPoints -->
