<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZCBLRLP0293" failures="2" tests="9" name="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" time="49.835" errors="0" timestamp="2024-06-27T16:14:13 IST" skipped="0">
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="testInvalidUsername_TestCase2" time="9.183">
    <failure message="The validation message not displaying for Invalid inputs expected [Invalid username or password. Try again.] but found [Invalid Username or Password. Try again.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The validation message not displaying for Invalid inputs expected [Invalid username or password. Try again.] but found [Invalid Username or Password. Try again.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at zapcg.Capillary.PageObject.loginPage.verifyInvalidUserNameError(loginPage.java:182)
at zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases.testInvalidUsername_TestCase2(Login_Invalid_TestCases.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testInvalidUsername_TestCase2 -->
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="testInvalidPassword_TestCase3" time="6.440">
    <failure message="The validation message not displaying for Invalid inputs expected [Invalid username or password. Try again.] but found [Invalid Username or Password. Try again.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The validation message not displaying for Invalid inputs expected [Invalid username or password. Try again.] but found [Invalid Username or Password. Try again.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at zapcg.Capillary.PageObject.loginPage.verifyInvalidPasswordError(loginPage.java:219)
at zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases.testInvalidPassword_TestCase3(Login_Invalid_TestCases.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testInvalidPassword_TestCase3 -->
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="testTooLongUsername_TestCase4" time="5.498"/>
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="testMinLengthPassword_TestCase5" time="4.280"/>
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="testUsernameWithSpaces_TestCase6" time="4.288"/>
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="verifyForEnabledLoginButton_TestCase7" time="5.769"/>
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="verifyForDisabledLoginButtonForEmptyUsername_TestCase8" time="4.315"/>
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="verifyForDisabledLoginButtonForEmptyPassword_TestCase9" time="4.598"/>
  <testcase classname="zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases" name="verifyForDisabledLoginButtonForEmptyUsernamePassword_TestCase10" time="5.464"/>
</testsuite> <!-- zapcg.Capillary.LoginTestCases.Login_Invalid_TestCases -->
