<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-15T12:39:40 IST" name="Fortress_TestSuite" finished-at="2024-07-15T12:39:51 IST" duration-ms="10818">
    <groups>
      <group name="OneTimeExecution">
        <method signature="OneTimeExecute_TransactionExceedsThreshold.TransactionExceedsThreshold()[pri:1, instance:zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold@60afd40d]" name="TransactionExceedsThreshold" class="zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold"/>
      </group> <!-- OneTimeExecution -->
    </groups>
    <test started-at="2024-07-15T12:39:40 IST" name="LoginTestsChromeBrowseriPhone11ProPortrait_OneTimeExecution" finished-at="2024-07-15T12:39:51 IST" duration-ms="10818">
      <class name="zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold">
        <test-method is-config="true" signature="initialize(java.lang.String,java.lang.String)[pri:0, instance:zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold@60afd40d]" started-at="2024-07-15T12:39:40 IST" name="initialize" finished-at="2024-07-15T12:39:48 IST" duration-ms="7877" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[iPhone 11 Pro Portrait]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="TransactionExceedsThreshold()[pri:1, instance:zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold@60afd40d]" started-at="2024-07-15T12:39:48 IST" name="TransactionExceedsThreshold" finished-at="2024-07-15T12:39:50 IST" duration-ms="2200" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected threshold message was not displayed correctly. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected threshold message was not displayed correctly. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold.TransactionExceedsThreshold(OneTimeExecute_TransactionExceedsThreshold.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TransactionExceedsThreshold -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold@60afd40d]" started-at="2024-07-15T12:39:50 IST" name="tearDown" finished-at="2024-07-15T12:39:51 IST" duration-ms="691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- zapcg.Capillary.EarnPointPageTestCases.OneTimeExecute_TransactionExceedsThreshold -->
    </test> <!-- LoginTestsChromeBrowseriPhone11ProPortrait_OneTimeExecution -->
  </suite> <!-- Fortress_TestSuite -->
</testng-results>
